refactored, got disk cleanup routine working

diff --git a/src/backmeup b/src/backmeup
--- a/src/backmeup
+++ b/src/backmeup
@@ -1,7 +1,31 @@
 #!/bin/zsh
-# -xv
+# backmeup
+# author: Jonathan Donald
+# License: GPL
+#
+# backup script
+# a convenience wrapper around the dar command
+#
+# dependencies
+#     awk
+#     cut
+#     dar
+#     df
+#     du
+#     echo
+#     grep
+#     mkdir
+#     realpath
+#     tail
+#     uname
+#     zsh
+#
+#-------------------------------------------------------------------------------------------------------
 
 # makes an incremental (aka differential) backup
+#    parameter 1: the backup destination directory
+#    parameter 2: the name (hostname) of the machine being backed up
+#    parameter 3: the current date/time stamp
 function incr_backup() {
     PARENT_BACKUP_DIR=$1
     MACHINE=$2
@@ -12,22 +36,22 @@ function incr_backup() {
     then
 	mkdir -p ${BACKUP_DIR}
     else
-	echo "backup directory ${BACKUP_DIR} already exists"
+	/bin/echo "backup directory ${BACKUP_DIR} already exists"
     fi
 
-    echo "making a differential backup to ${BACKUP_DIR}/"
+    /bin/echo "making a differential backup to ${BACKUP_DIR}/"
     BACKUP_ARCHIVE="${BACKUP_DIR}/${MACHINE}-${DATESTAMP}-DIFF"
-    PREV_ARCH_DIR=`/bin/ls -1t ${PARENT_BACKUP_DIR} | grep FULL | /usr/bin/tail -n 1`
-    PREV_ARCH_FILE=`ls -1tr ${PARENT_BACKUP_DIR}/${PREV_ARCH_DIR} | /usr/bin/tail -n 1`
+    PREV_ARCH_DIR=`/bin/ls -1t ${PARENT_BACKUP_DIR} | /bin/grep FULL | /usr/bin/tail -n 1`
+    PREV_ARCH_FILE=`/bin/ls -1tr ${PARENT_BACKUP_DIR}/${PREV_ARCH_DIR} | /usr/bin/tail -n 1`
     # derive the previous backup set from the previous archive file name
-    LEN=`echo $PREV_ARCH_FILE | wc -c`
+    LEN=`/bin/echo $PREV_ARCH_FILE | wc -c`
     let "TRUNC_LEN=$LEN-9"
     CHARTEST=`cut $PREV_ARCH_FILE $TRUNC_LEN`
     #if [[ $CHARTEST == '.'  ]]
     #then
     #   let "TRUNC_LEN=$LEN-9"
     #fi
-    PREV_ARCH_BASE=`echo $PREV_ARCH_FILE | cut -c 1-$TRUNC_LEN`
+    PREV_ARCH_BASE=`/bin/echo $PREV_ARCH_FILE | cut -c 1-$TRUNC_LEN`
 
     dar -v \
 	-s $MAX_SIZE \
@@ -36,11 +60,14 @@ function incr_backup() {
 	-A ${PARENT_BACKUP_DIR}/${PREV_ARCH_DIR}/${PREV_ARCH_BASE} -R /  \
         -B ${CFG_FILE}
     donetime=`date`
-    echo "Differential backup $BACKUP_ARCHIVE completed at ${donetime}"
-    echo "backed up to `/usr/bin/du -sh ${BACKUP_DIR}`"
+    /bin/echo "Differential backup $BACKUP_ARCHIVE completed at ${donetime}"
+    /bin/echo "backed up to `/usr/bin/du -sh ${BACKUP_DIR}`"
 }
 
 # makes a full backup
+#    parameter 1: the backup destination directory
+#    parameter 2: the name (hostname) of the machine being backed up
+#    parameter 3: the current date/time stamp
 function full_backup() {
     BACKUP_DIR=$1
     MACHINE=$2
@@ -51,10 +78,10 @@ function full_backup() {
     then
 	mkdir -p ${BACKUP_DIR}
     else
-	echo "backup directory ${BACKUP_DIR} already exists"
+	/bin/echo "backup directory ${BACKUP_DIR} already exists"
     fi
 
-    echo "making a full backup to ${BACKUP_DIR}/"
+    /bin/echo "making a full backup to ${BACKUP_DIR}/"
     BACKUP_ARCHIVE="${BACKUP_DIR}/${MACHINE}-${DATESTAMP}-FULL"
     dar -v \
 	-s $MAX_SIZE \
@@ -62,53 +89,84 @@ function full_backup() {
 	-R / \
         -B ${CFG_FILE}
     donetime=`date`
-    echo "Full backup ${BACKUP_ARCHIVE} completed at ${donetime}"
-    echo "backed up to `/usr/bin/du -sh ${BACKUP_DIR}`"
+    /bin/echo "Full backup ${BACKUP_ARCHIVE} completed at ${donetime}"
+    /bin/echo "backed up to `/usr/bin/du -sh ${BACKUP_DIR}`"
 }
 
-# TODO make this work
+# given a directory or file, this tells you what mount point it lives on
+#    parameter 1: the directory or file path
+function get_mount_point() {
+    DIR=$1
+    FULL_PATH=`/usr/bin/realpath ${DIR}`
+    DRIVE=`df ${FULL_PATH} | awk 'END{print $6}'`
+    /bin/echo ${DRIVE}
+    }
+
 # should delete oldest backup sets in chronological order 
 # until there is ${MIN_FREE} bytes of free space
+#    parameter 1: the backup directory path
+#    parameter 2: the minimum amount of free space required
+#    parameter 3: the drive (mount point) on which to check free space
 function cleanup() {
     BACKUP_DIR=$1
     MIN_FREE=$2
+    DRIVE=$3
 
     # build a list of backups in oldest -> newest order
-    BACKUPS=(`ls -1 ${BACKUP_DIR} | grep ${MACHINE} | awk '{print substr($1,0,23)}' | uniq`)
+    BACKUPS=(`/bin/ls -1tr ${BACKUP_DIR}`)
 
     # loop through backups
     for i in ${BACKUPS}; do
-	#echo "\n\ni = $i" #DEBUG
-	size=`du ${BACKUP_DIR}/$i* |  awk '{ sum += $0 } END { print sum }'`
-	sizeh=`du -h ${BACKUP_DIR}/$i* |  awk '{ sum += $0 } END { print sum }'`
-	#echo "size = $size" #DEBUG
-	echo "deleting ${BACKUP_DIR}/$i* (${sizeh}M)"
-	rm -rf $i*	
-	DRIVE_FREE=`df | grep ${DRIVE} | awk '{print $4}'`
+	size=`/usr/bin/du ${BACKUP_DIR}/$i* |  /usr/bin/awk '{ sum += $0 } END { print sum }'`
+	sizeh=`/usr/bin/du -h ${BACKUP_DIR}/$i* |  /usr/bin/awk '{ sum += $0 } END { print sum }'`
+	/bin/echo "deleting ${BACKUP_DIR}/$i* (${sizeh}M)"
+	/bin/echo "/bin/rm -rf ${BACKUP_DIR}/$i*"
+	DRIVE_FREE=`df | /bin/grep ${DRIVE} | awk '{print $4}'`
 
        # break out, if there is at least ${MIN_FREE} free bytes
-        if [[ ( ${DRIVE_FREE} -gt ${MIN_FREE} ) ]]
+        if [[ ( ${DRIVE_FREE} -ge ${MIN_FREE} ) ]]
 	then
 	    break
 	fi
         # otherwise, delete the next oldest backup
     done
-    drive_freeh=`df -h | grep ${DRIVE} | awk '{print $4}'`
-    echo "Now have ${drive_freeh} free space"
+    drive_freeh=`df -h | /bin/grep ${DRIVE} | awk '{print $4}'`
+    /bin/echo "Now has ${drive_freeh} free space"
 }
 
+# returns 1 if there is sufficient free space or 0 if there is not
+# TODO externalize MIN_FREE_PERCENT
+#    parameter 1: the drive (mount point) on which to check free space
+function have_sufficient_free_space() {
+    DRIVE=$1
+    
+    DRIVE_TOTAL_BLOCKS=`/bin/df -k | /bin/grep ${DRIVE} | awk '{print $2}'`
+
+    MIN_FREE_PERCENT=.8
+    MIN_FREE_BLOCKS=$(($DRIVE_TOTAL_BLOCKS * $MIN_FREE_PERCENT)) 
+    MIN_FREE_BLOCKS=${MIN_FREE_BLOCKS:0:-1} #strip that ^#@$ trailing decimal point
+    
+    DRIVE_FREE_BLOCKS=`/bin/df -k | /bin/grep ${DRIVE} | awk '{print $4}'`
+
+    if [[ ( ${DRIVE_FREE_BLOCKS} -le ${MIN_FREE_BLOCKS} ) ]]
+    then
+        /bin/echo 1
+    else
+        /bin/echo 0
+    fi
+}
 
 function usage() {
-    echo "Usage:\n"
-    echo "\tbackmeup "
-    echo "\t\t-f {configuration file} "
-    echo "\t\t-d {backup directory} "
-    echo "\t\t-t {backup type} \n"
-    echo "arguments:\n"
-    echo "\t{backup type} is full | diff"
-    echo "\t\tfull does a full backup of everything specified in the configuration file"
-    echo "\t\tdiff does an incremental backup of everything specified in the configuration file based on the changes made since the last backup\n"
-    echo "\n\nexample:\n\tbackmeup -f ~/.backmeup.cfg -d /media/jdonald/BACKUP4T/backup/armenelos -t diff"
+    /bin/echo "Usage:\n"
+    /bin/echo "\tbackmeup "
+    /bin/echo "\t\t-f {configuration file} "
+    /bin/echo "\t\t-d {backup directory} "
+    /bin/echo "\t\t-t {backup type} \n"
+    /bin/echo "arguments:\n"
+    /bin/echo "\t{backup type} is full | diff"
+    /bin/echo "\t\tfull does a full backup of everything specified in the configuration file"
+    /bin/echo "\t\tdiff does an incremental backup of everything specified in the configuration file based on the changes made since the last backup\n"
+    /bin/echo "\n\nexample:\n\tbackmeup -f ~/.backmeup.cfg -d /media/jdonald/BACKUP4T/backup/armenelos -t diff"
 }
 
 # ---------------------------------------------------------
@@ -116,20 +174,14 @@ function usage() {
 MACHINE=`uname -n`
 BACKUP_NAME="${MACHINE}"
 MIN_FREE=200000000
-MAX_SIZE="256M"
-
-#DRIVE="/media/backupdrive"
-#PARENT_BACKUP_DIR="${DRIVE}/backup/${MACHINE}"
-
+MAX_SIZE="512M"
 
 if (( $# != 6 ))
 then
-    echo "wrong number of arguments passed"
+    /bin/echo "wrong number of arguments passed"
     usage
     exit 1
 fi
-
-
 
 # : indicates the preceding letter option requires a parameter
 while getopts "f:d:t:h" opt; 
@@ -137,97 +189,65 @@ do
     case ${opt} in
 	f )
 	    CFG_FILE=${OPTARG}
-	    echo "CFG_FILE=$CFG_FILE"
+	    /bin/echo "CFG_FILE=$CFG_FILE"
 	    ;;
-	: ) echo "$0: Must supply an argument to -${OPTARG}"
+	: ) /bin/echo "$0: Must supply an argument to -${OPTARG}"
          exit 1
          ;;
 	d )
             PARENT_BACKUP_DIR=${OPTARG}
             ;;
-	: ) echo "$0: Must supply an argument to -${OPTARG}"
+	: ) /bin/echo "$0: Must supply an argument to -${OPTARG}"
          exit 1
           ;;
 	t )
 	    TYPE=${OPTARG}
-	    echo "TYPE=$TYPE"
+	    /bin/echo "TYPE=$TYPE"
 	    ;;
-	: ) echo "$0: Must supply an argument to -${OPTARG}"
+	: ) /bin/echo "$0: Must supply an argument to -${OPTARG}"
          exit 1
           ;;
 	h )
 	    usage
 	    ;;
-       *) echo "Invalid option -${OPTARG} ignored"
+        * ) /bin/echo "Invalid option -${OPTARG} ignored"
 	     usage
 	     exit 1
 	 ;;
-	\? ) echo "Invalid option -${OPTARG} ignored"
+	\? ) /bin/echo "Invalid option -${OPTARG} ignored"
 	     usage
 	     exit 1
 	 ;;
     esac
 done
 
-# if [ $OPTIND -eq 1 ]
-#then
-#    echo "No options were passed"
-#    usage
-#    exit 1
-#fi
-
 if [[ -d "${PARENT_BACKUP_DIR}" ]]
 then
-    echo ""
+    /bin/echo ""
 else
-    echo "${PARENT_BACKUP_DIR} is not a directory" >&2
+    /bin/echo "${PARENT_BACKUP_DIR} is not a directory" >&2
     exit 1
 fi
 
 if [[ ${PARENT_BACKUP_DIR} == "" ]]
 then
-    echo "no parent backup directory specified"
-    exit
+    /bin/mkdir -p ${PARENT_BACKUP_DIR}
 fi
 
 
+DRIVE=`get_mount_point ${PARENT_BACKUP_DIR}`
 
-# abort if backup drive isn't actually mounted
-#lookupmount=`mount -l | grep "${DRIVE}"`
-#mounted=`echo $lookupmount | awk '{print $3}'`
+freeness=`have_sufficient_free_space ${DRIVE}`
 
-#if [[ (  ${mounted} != ${DRIVE} ) ]]
-#then
-#    echo "backup volume ${DRIVE} is not mounted!"
-#    exit 1
-#fi
-
-
-# check to see if $PARENT_BACKUP_DIR exists
-if [ ! -d ${PARENT_BACKUP_DIR} ]
+if [[  ${freeness} -eq 1 ]]
 then
-    mkdir -p ${PARENT_BACKUP_DIR}
+    /bin/echo "plenty of free space on ${DRIVE}"
 else
-    echo "backup directory ${PARENT_BACKUP_DIR} already exists"
+    /bin/echo "not enough free space on ${DRIVE}"
+    cleanup ${PARENT_BACKUP_DIR}/${MACHINE} ${MIN_FREE_BLOCKS} ${DRIVE}
 fi
-
-echo "cleaning up ${PARENT_BACKUP_DIR} to remove any empty directories"
-rmdir -v ${PARENT_BACKUP_DIR}/*
-
-# how much free space there is on ${DRIVE}
-#DRIVE_FREE=`df | grep ${DRIVE} | awk '{print $4}'`
-
-#if [[ ( ${DRIVE_FREE} -lt ${MIN_FREE} )  ]]
-#then
-#    echo "not enough free space on ${DRIVE}"
-#    cleanup ${PARENT_BACKUP_DIR} ${MIN_FREE}
-#else
-#    echo "plenty of free space on ${DRIVE}"
-#fi
 
 DATESTAMP=`date +%Y%m%d-%H%M`
-
-
 
 if [[ ( $TYPE != "full" ) && ( $TYPE != "FULL" ) ]] 
 then
@@ -235,6 +255,10 @@ then
 else
     full_backup ${PARENT_BACKUP_DIR} ${MACHINE} ${DATESTAMP}
 fi
+
+
+
+
 
 
 
